version: '3'

services:
  reverseproxy:
    image: airondev/udagram-reverseproxy
    build: ../udagram-reverseproxy
    ports:
        - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-feed:
    image: airondev/udagram-feed-api
    build: ../udagram-feed-api
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  backend-user:
    image: airondev/udagram-users-api
    build: ../udagram-users-api
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  frontend:
    image: airondev/udagram-frontend
    build: ../udagram-frontend
    ports:
      - "8100:80"
